### ISSUE TITLE
How do we set the user information with SPM?

### ISSUE THREAD

**Issue by bilaldurnagol** [namiml/NamiSDK-SwiftPackageManager#15]
_When I want to set user information. I get error Type 'NamiCustomerManager' has no member 'setCustomerAttribute'_

**How can I set user information?**

![Screenshot 2023-03-12 at 12 50 21](https://user-images.githubusercontent.com/25571364/224537208-b14e8389-4913-4e03-b733-ba13b92997cb.png)

**Comment by HelloNamiML** [comment]
Hi @bilaldurnagol,

The `main` branch has been updated with version 3.0.7 of the SDK, which has these methods.
If you update SPM from `main`, you should bee in good shape.
