### ISSUE TITLE
How do i show full screen paywall?

### ISSUE THREAD

**Issue by bilaldurnagol** [namiml/NamiSDK-SwiftPackageManager#16]
**I am using the code below. but paywall is not full screen.** _**How do I make a full screen paywall?**_

` namiConfig.fullScreenPresentation = false`

**Comment by HelloNamiML** [comment]
Hi @bilaldurnagol 

We're moving control of full-screen vs. non-fullscreen to the Paywall CMS in the Nami Control Center, so that namiConfig property does not need to be set. 

If you could reach out to us at support@nami.ml we can help you get your Paywall setup for this.
